# include "Resources_CA/I2C_V17_CA.h"
# include "Resources_CA/I2C_V17_CA_IO_subroutines.c"
# include "Resources_CA/I2C_V17_CA_display_subroutines.c"
# include "Resources_CA/I2C_V17_CA_Arithmetic_subroutines.c"
# include "Resources_CA/I2C_V17_CA_ISR_subroutines.c"
# include "Resources_CA/I2C_V17_CA_osccal_calibration subroutintes.c"
# include "Resources_CA/I2C_V17_CA_modes_B_to_F.c"

# include "Resources_CA/I2C_V17_CA_clock_stop_watch_subroutines.c"
# include "Resources_CA/I2C_V17_CA_Eeprom_subroutines.c"
# include "Resources_CA/I2C_V17_CA_mode_definitions.h"